"""Add leads and enrollments tables

Revision ID: 8db7b9d366f2
Revises: f32a86e49de6
Create Date: 2026-01-24 23:48:26.422988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db7b9d366f2'
down_revision: Union[str, None] = 'f32a86e49de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_center_id'), 'batches', ['center_id'], unique=False)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('children',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_center_id'), 'children', ['center_id'], unique=False)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('parents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_center_id'), 'parents', ['center_id'], unique=False)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_phone'), 'parents', ['phone'], unique=False)
    op.create_table('class_sessions',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('trainer_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sessions_batch_id'), 'class_sessions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_center_id'), 'class_sessions', ['center_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_id'), 'class_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_class_sessions_session_date'), 'class_sessions', ['session_date'], unique=False)
    op.create_table('enrollments',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.Enum('PAY_PER_VISIT', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM', name='plantype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('visits_included', sa.Integer(), nullable=True),
    sa.Column('visits_used', sa.Integer(), nullable=False),
    sa.Column('days_selected', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'PAUSED', name='enrollmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_center_id'), 'enrollments', ['center_id'], unique=False)
    op.create_index(op.f('ix_enrollments_child_id'), 'enrollments', ['child_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_table('family_links',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_links_center_id'), 'family_links', ['center_id'], unique=False)
    op.create_index(op.f('ix_family_links_child_id'), 'family_links', ['child_id'], unique=False)
    op.create_index(op.f('ix_family_links_id'), 'family_links', ['id'], unique=False)
    op.create_index(op.f('ix_family_links_parent_id'), 'family_links', ['parent_id'], unique=False)
    op.create_table('leads',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERY', 'INTRO_SCHEDULED', 'INTRO_ATTENDED', 'NO_SHOW', 'FOLLOW_UP', 'DEAD_LEAD', 'ENROLLED', name='leadstatus'), nullable=False),
    sa.Column('source', sa.Enum('WALK_IN', 'REFERRAL', 'INSTAGRAM', 'FACEBOOK', 'GOOGLE', 'OTHER', name='leadsource'), nullable=True),
    sa.Column('discovery_notes', sa.Text(), nullable=True),
    sa.Column('dead_lead_reason', sa.String(length=500), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_center_id'), 'leads', ['center_id'], unique=False)
    op.create_index(op.f('ix_leads_child_id'), 'leads', ['child_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('attendance',
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'MAKEUP', 'TRIAL', 'CANCELLED', name='attendancestatus'), nullable=False),
    sa.Column('marked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_center_id'), 'attendance', ['center_id'], unique=False)
    op.create_index(op.f('ix_attendance_child_id'), 'attendance', ['child_id'], unique=False)
    op.create_index(op.f('ix_attendance_class_session_id'), 'attendance', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_attendance_enrollment_id'), 'attendance', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('discounts',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PERCENT', 'FLAT', name='discounttype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_center_id'), 'discounts', ['center_id'], unique=False)
    op.create_index(op.f('ix_discounts_enrollment_id'), 'discounts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.create_table('intro_visits',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('trainer_user_id', sa.Integer(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['trainer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intro_visits_center_id'), 'intro_visits', ['center_id'], unique=False)
    op.create_index(op.f('ix_intro_visits_id'), 'intro_visits', ['id'], unique=False)
    op.create_index(op.f('ix_intro_visits_lead_id'), 'intro_visits', ['lead_id'], unique=False)
    op.create_table('payments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_center_id'), 'payments', ['center_id'], unique=False)
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_center_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_intro_visits_lead_id'), table_name='intro_visits')
    op.drop_index(op.f('ix_intro_visits_id'), table_name='intro_visits')
    op.drop_index(op.f('ix_intro_visits_center_id'), table_name='intro_visits')
    op.drop_table('intro_visits')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_enrollment_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_center_id'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_enrollment_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_class_session_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_child_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_center_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_child_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_center_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_family_links_parent_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_child_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_center_id'), table_name='family_links')
    op.drop_table('family_links')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_child_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_center_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_class_sessions_session_date'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_center_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_batch_id'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_parents_phone'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_center_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index(op.f('ix_children_center_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_center_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
