from app.schemas.auth import LoginRequest, LoginResponse, Token, UserResponse
from app.schemas.lead import (
    ParentCreate,
    ParentResponse,
    ChildCreate,
    ChildResponse,
    FamilyLinkCreate,
    FamilyLinkResponse,
    LeadCreate,
    LeadUpdate,
    LeadMarkDead,
    LeadResponse,
    LeadDetailResponse,
    IntroVisitCreate,
    IntroVisitMarkAttended,
    IntroVisitResponse,
)
from app.schemas.enrollment import (
    BatchCreate,
    BatchResponse,
    DiscountCreate,
    DiscountResponse,
    PaymentCreate,
    PaymentResponse,
    EnrollmentCreate,
    EnrollmentUpdate,
    EnrollmentResponse,
    EnrollmentDetailResponse,
)
from app.schemas.attendance import (
    ClassSessionCreate,
    ClassSessionUpdate,
    ClassSessionResponse,
    AttendanceCreate,
    AttendanceBulkCreate,
    AttendanceUpdate,
    AttendanceResponse,
)
from app.schemas.curriculum import (
    CurriculumCreate,
    CurriculumUpdate,
    CurriculumResponse,
    CurriculumWithSkills,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
    SkillProgressCreate,
    SkillProgressBulkUpdate,
    SkillProgressUpdate,
    SkillProgressResponse,
    SkillProgressWithDetails,
)
from app.schemas.report_card import (
    ReportCardCreate,
    ReportCardResponse,
    ReportCardWithChild,
)

__all__ = [
    "LoginRequest",
    "LoginResponse",
    "Token",
    "UserResponse",
    "ParentCreate",
    "ParentResponse",
    "ChildCreate",
    "ChildResponse",
    "FamilyLinkCreate",
    "FamilyLinkResponse",
    "LeadCreate",
    "LeadUpdate",
    "LeadMarkDead",
    "LeadResponse",
    "LeadDetailResponse",
    "IntroVisitCreate",
    "IntroVisitMarkAttended",
    "IntroVisitResponse",
    "BatchCreate",
    "BatchResponse",
    "DiscountCreate",
    "DiscountResponse",
    "PaymentCreate",
    "PaymentResponse",
    "EnrollmentCreate",
    "EnrollmentUpdate",
    "EnrollmentResponse",
    "EnrollmentDetailResponse",
]
